Traceback (most recent call last):
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/samuel.oranyeli/mambaforge/envs/blogger/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#ensure 7z is already installed on your system
df = fread(cmd = "7z e -so Data_files/iris_single_7z.7z")

df.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[9], line 2[0m
[1;32m      1[0m [38;5;66;03m#ensure 7z is already installed on your system[39;00m
[0;32m----> 2[0m df [38;5;241m=[39m [43mfread[49m[43m([49m[43mcmd[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43m7z e -so Data_files/iris_single_7z.7z[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      4[0m df[38;5;241m.[39mhead()

File [0;32m~/mambaforge/envs/blogger/lib/python3.10/site-packages/datatable/utils/fread.py:348[0m, in [0;36m_resolve_source_cmd[0;34m(cmd)[0m
[1;32m    346[0m [38;5;28;01mif[39;00m ret:
[1;32m    347[0m     msgerr [38;5;241m=[39m msgerr[38;5;241m.[39mdecode([38;5;124m"[39m[38;5;124mutf-8[39m[38;5;124m"[39m, errors[38;5;241m=[39m[38;5;124m"[39m[38;5;124mreplace[39m[38;5;124m"[39m)[38;5;241m.[39mstrip()
[0;32m--> 348[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mShell command returned error code [39m[38;5;132;01m%r[39;00m[38;5;124m: `[39m[38;5;132;01m%s[39;00m[38;5;124m`[39m[38;5;124m"[39m
[1;32m    349[0m                      [38;5;241m%[39m (ret, msgerr))
[1;32m    350[0m [38;5;28;01melse[39;00m:
[1;32m    351[0m     [38;5;66;03m# src, file, fileno, text, result[39;00m
[1;32m    352[0m     [38;5;28;01mreturn[39;00m (cmd, [38;5;28;01mNone[39;00m, [38;5;28;01mNone[39;00m, msgout), [38;5;28;01mNone[39;00m

[0;31mValueError[0m: Shell command returned error code 127: /bin/sh: 7z: command not found
ValueError: Shell command returned error code 127: /bin/sh: 7z: command not found

